# Imagen base oficial de Node.js
FROM node:20

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia todos los archivos del proyecto al contenedor
COPY . .

# Instala las dependencias del proyecto
RUN npm install

# Genera los clientes Prisma para ambos esquemas
RUN npx prisma generate --schema=prisma/mariadbBill/schema.prisma

RUN apt-get update && apt-get install -y netcat-openbsd

# Aplica las migraciones (db push) para ambas bases de datos
# RUN npx prisma db push --schema=prisma/mariadbBill/schema.prisma

# Expone el puerto en el que corre la aplicación
EXPOSE 3005
# Copiar entrypoint y darle permisos

COPY entrypoint2.sh /usr/local/bin/entrypoint2.sh
RUN chmod +x /usr/local/bin/entrypoint2.sh

ENTRYPOINT ["entrypoint2.sh"]

CMD ["npm", "start"]