# Imagen base oficial de Node.js
FROM node:20

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia todos los archivos del proyecto al contenedor
COPY . .

# Instala las dependencias del proyecto
RUN npm install

# Genera los clientes Prisma para ambos esquemas
RUN npx prisma generate --schema=prisma/mariadbBill/schema.prisma

# Aplica las migraciones (db push) para ambas bases de datos
# RUN npx prisma db push --schema=prisma/mariadbBill/schema.prisma

# Expone el puerto en el que corre la aplicación
EXPOSE 3005

# Comando por defecto para ejecutar la aplicación
CMD ["npm", "start"]
