# Dockerfile para API Gateway

FROM node:18

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar archivos de proyecto
COPY . .

# Instalar dependencias
RUN npm install

# Exponer el puerto que usará la Gateway
EXPOSE 3001

# Ejecutar la aplicación
CMD ["npm", "start"]
