services:
  nginx:
    image: nginx:latest
    container_name: nginx-taller
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/comedia.js:/etc/nginx/njs/comedia.js:ro
      - ./nginx/postdata.log:/var/log/nginx/postdata.log
      - ./nginx/mycert.pem:/etc/nginx/ssl/mycert.pem:ro
      - ./nginx/mykey.pem:/etc/nginx/ssl/mykey.pem:ro