# Imagen base oficial de Node.js
FROM node:20

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar todos los archivos del proyecto al contenedor
COPY . .

RUN apt-get update && apt-get install -y netcat

# Instalar dependencias del proyecto
RUN npm install

# Generar cliente Prisma
RUN npx prisma generate --schema=prisma/mariadb/schema.prisma

# Copiar entrypoint y darle permisos
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

CMD ["npm", "start"]
