# Imagen base oficial de Node.js
FROM node:20

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar todos los archivos del proyecto al contenedor
COPY . .

# Instalar las dependencias
RUN npm install

# Exponer el puerto donde corre la aplicación
EXPOSE 3004

# Comando por defecto para ejecutar la aplicación
CMD ["npm", "start"]
