# Imagen base oficial de Node.js
FROM node:20

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar todos los archivos del proyecto al contenedor
COPY . .

# Instalar dependencias del proyecto
RUN npm install

# Generar los clientes Prisma para ambas bases de datos
RUN npx prisma generate --schema=prisma/mariadb/schema.prisma \
  && npx prisma generate --schema=prisma/postgres/schema.prisma

# Realizar las migraciones (db push) para ambas bases de datos
# RUN npx prisma db push --schema=prisma/mariadb/schema.prisma \
#   && npx prisma db push --schema=prisma/postgres/schema.prisma

# Exponer el puerto en el que corre la aplicación
EXPOSE 3002

# Comando por defecto para ejecutar la aplicación
CMD ["npm", "start"]
