name: Docker Push Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push_all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push MS-Videos
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-videos:latest ./Videos
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-videos:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/ms-videos:latest ${{ secrets.DOCKER_USERNAME }}/ms-videos:${{ github.sha }}

      - name: Build & Push MS-Usuarios
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-usuarios:latest ./Usuarios
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-usuarios:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/ms-usuarios:latest ${{ secrets.DOCKER_USERNAME }}/ms-usuarios:${{ github.sha }}

      - name: Build & Push MS-Auth
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-auth:latest ./Autenticacion
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-auth:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/ms-auth:latest ${{ secrets.DOCKER_USERNAME }}/ms-auth:${{ github.sha }}

      - name: Build & Push MS-Bills
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-bills:latest ./Bills
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-bills:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/ms-bills:latest ${{ secrets.DOCKER_USERNAME }}/ms-bills:${{ github.sha }}

      - name: Build & Push MS-Interaccion
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-interaccion:latest ./InteraccionSocial
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-interaccion:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/ms-interaccion:latest ${{ secrets.DOCKER_USERNAME }}/ms-interaccion:${{ github.sha }}

      - name: Build & Push MS-Monitoreo
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms-monitoreo:latest ./Monitoreo
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-monitoreo:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/ms-monitoreo:latest ${{ secrets.DOCKER_USERNAME }}/ms-monitoreo:${{ github.sha }}
